version: '3'
services:
  app:
    build: app/
    volumes:
      - "./app:/app"
      - "/app/node_modules"
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
  api:
    build: api/
    ports:
      - "5000:5000"
  db:
    build: db/
    ports:
      - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: makermap-db
