version: '3'
services:
  api:
    build: api/
    ports:
      - "5000:5000"
  db:
    build: db/
    ports:
      - "3306:3306"    
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: makermap-db
